### ISSUE TITLE
Unable to setup XDP using vagrant due to repo issues.

### ISSUE THREAD

**Issue by harsha176** [iovisor/xdp-vagrant#6]
Hi,

I'm trying to setup XDP using vagrant by running the script. It is failing to fetch package list from repo server hosted on 52.8.15.63. It looks like something is wrong with the server.

Can you help me resolve the issue? 

Thanks,
Harsha

Details:

File: setup-apt.sh
...
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D4284CDD
echo "deb [trusted=yes] http://52.8.15.63/apt trusty kernel" | tee /etc/apt/sources.list.d/iovisor.list
echo "deb [trusted=yes] http://52.8.15.63/apt/trusty trusty-nightly main" | tee -a /etc/apt/sources.list.d/iovisor.list
...

Error:

#apt-get update
...
==> default: Ign http://52.8.15.63 trusty-nightly InRelease
==> default: Ign http://52.8.15.63 trusty Release.gpg
==> default: Ign http://52.8.15.63 trusty-nightly Release.gpg
==> default: Ign http://52.8.15.63 trusty Release
==> default: Ign http://52.8.15.63 trusty-nightly Release
==> default: Err http://52.8.15.63 trusty/kernel amd64 Packages
==> default:   504  Gateway Time-out
==> default: Ign http://52.8.15.63 trusty/kernel Translation-en_US
==> default: Ign http://52.8.15.63 trusty/kernel Translation-en
==> default: Err http://52.8.15.63 trusty-nightly/main amd64 Packages
==> default:   504  Gateway Time-out
...

**Comment by drzaeus77** [comment]
Hmm, that static IP address is out of date, it should be https://repo.iovisor.org as per https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu-xenial---binary

**Comment by thnam91** [comment]
I changed the static IP address to `https://repo.iovisor.org` on PR #7. Then I tested the setup-apt.sh file. It works well :D
